# Generated by Django 3.2.1 on 2023-02-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codersmotivation', '0002_auto_20230125_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='post',
        ),
    ]
