# Generated by Django 3.2.1 on 2023-02-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codersmotivation', '0003_auto_20230205_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='@user.com', max_length=254),
        ),
    ]
