# Generated by Django 3.2.1 on 2023-02-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codersmotivation', '0004_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
