# Generated by Django 3.2.1 on 2023-02-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codersmotivation', '0006_auto_20230221_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
