# Generated by Django 3.2.1 on 2023-02-22 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codersmotivation', '0007_auto_20230221_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='codersmotivation.post'),
            preserve_default=False,
        ),
    ]
